const ASSETS_ACCOUNT_LOADING = 'BALANCE_LOADING';
const ASSETS_ACCOUNT_SUCCESS = 'ASSETS_ACCOUNT_SUCCESS';
const ASSETS_ACCOUNT_FAILURE = 'ASSETS_ACCOUNT_FAILURE';

export const assetsAccountActions = {
  ASSETS_ACCOUNT_LOADING,
  ASSETS_ACCOUNT_SUCCESS,
  ASSETS_ACCOUNT_FAILURE,
};
