
export const assetsAccountActions = {
  LOADING: 'ASSETS_ACCOUNT_LOADING',
  SUCCESS: 'ASSETS_ACCOUNT_SUCCESS',
  FAILURE: 'ASSETS_ACCOUNT_FAILURE',
};


export const listOffersAccountActions = {
  LOADING: 'LIST_OFFERS_ACCOUNT_LOADING',
  SUCCESS: 'LIST_OFFERS_ACCOUNT_SUCCESS',
  FAILURE: 'LIST_OFFERS_ACCOUNT_FAILURE',
};

export const listingsAccountActions = {
  LOADING: 'LISTINGS_ACCOUNT_LOADING',
  SUCCESS: 'LISTINGS_ACCOUNT_SUCCESS',
  FAILURE: 'LISTINGS_ACCOUNT_FAILURE',
};
