export const listCollectionActions = {
  LOADING: 'LIST_COLLECTION_LOADING',
  SUCCESS: 'LIST_COLLECTION_SUCCESS',
  FAILURE: 'LIST_COLLECTION_FAILURE',
};

export const listOfferActions = {
  LOADING: 'LIST_OFFER_LOADING',
  SUCCESS: 'LIST_OFFER_SUCCESS',
  FAILURE: 'LIST_OFFER_FAILURE',
};

export const itemsCollectionActions = {
  LOADING: 'ITEMS_COLLECTION_LOADING',
  SUCCESS: 'ITEMS_COLLECTION_SUCCESS',
  FAILURE: 'ITEMS_COLLECTION_FAILURE',
};

export const activitiesCollectionActions = {
  LOADING: 'ACTIVITIES_COLLECTION_LOADING',
  SUCCESS: 'ACTIVITIES_COLLECTION_SUCCESS',
  FAILURE: 'ACTIVITIES_COLLECTION_FAILURE',
};
