export const hotCollectionsActions = {
  HOT_COLLECTION_LOADING: 'HOT_COLLECTION_LOADING',
  HOT_COLLECTION_SUCCESS: 'HOT_COLLECTION_SUCCESS',
  HOT_COLLECTION_FAILURE: 'HOT_COLLECTION_FAILURE',
};

export const bigOfferActions = {
  BIG_OFFER_LOADING: 'BIG_OFFER_LOADING',
  BIG_OFFER_SUCCESS: 'BIG_OFFER_SUCCESS',
  BIG_OFFER_FAILURE: 'BIG_OFFER_FAILURE',
};
