export const itemsProjectCollectionActions = {
    LOADING: 'ITEMS_PROJECT_COLLECTION_LOADING',
    SUCCESS: 'ITEMS_PROJECT_COLLECTION_SUCCESS',
    FAILURE: 'ITEMS_PROJECT_COLLECTION_FAILURE',
};

export const activitiesProjectCollectionActions = {
    LOADING: 'ACTIVITIES_PROJECT_COLLECTION_LOADING',
    SUCCESS: 'ACTIVITIES_PROJECT_COLLECTION_SUCCESS',
    FAILURE: 'ACTIVITIES_PROJECT_COLLECTION_FAILURE',
};

export const projectInforActions = {
    LOADING: 'PROJECT_INFOR_LOADING',
    SUCCESS: 'PROJECT_INFOR_SUCCESS',
    FAILURE: 'PROJECT_INFOR_FAILURE',
};

export const activitiesDetailCollectionActions = {
    LOADING: 'ACTIVITIES_DETAIL_COLLECTION_LOADING',
    SUCCESS: 'ACTIVITIES_DETAIL_COLLECTION_SUCCESS',
    FAILURE: 'ACTIVITIES_DETAIL_COLLECTION_FAILURE',
};
