export const itemsProjectCollectionActions = {
    ITEMS_PROJECT_COLLECTION_LOADING: 'ITEMS_PROJECT_COLLECTION_LOADING',
    ITEMS_PROJECT_COLLECTION_SUCCESS: 'ITEMS_PROJECT_COLLECTION_SUCCESS',
    ITEMS_PROJECT_COLLECTION_FAILURE: 'ITEMS_PROJECT_COLLECTION_FAILURE',
};

export const activitiesProjectCollectionActions = {
    ACTIVITIES_PROJECT_COLLECTION_LOADING: 'ACTIVITIES_PROJECT_COLLECTION_LOADING',
    ACTIVITIES_PROJECT_COLLECTION_SUCCESS: 'ACTIVITIES_PROJECT_COLLECTION_SUCCESS',
    ACTIVITIES_PROJECT_COLLECTION_FAILURE: 'ACTIVITIES_PROJECT_COLLECTION_FAILURE',
};

export const projectInforActions = {
    PROJECT_INFOR_LOADING: 'PROJECT_INFOR_LOADING',
    PROJECT_INFOR_SUCCESS: 'PROJECT_INFOR_SUCCESS',
    PROJECT_INFOR_FAILURE: 'PROJECT_INFOR_FAILURE',
};

