export const CATEGORY = [
  {
    id: 1,
    title: "Blockchain sections",
    level: 1,
    list: [
      { id: 1, title: "Free to Play" },
      { id: 2, title: "Play to Earn" },
      { id: 3, title: "Staking" },
      { id: 4, title: "NFT Farming" },
      { id: 5, title: "NFT Renting" },
      { id: 6, title: "Gacha system" },
      { id: 7, title: "Governance" },
      { id: 8, title: "Collectible Games" },
    ],
    show: false,
  },
  {
    id: 2,
    title: "SPECIAL SECTIONS",
    level: 1,
    list: [
      { id: 9, title: "Demos" },
      { id: 10, title: "Early Access" },
      { id: 11, title: "Controller Friendly" },
      { id: 12, title: "Remote Play" },
      { id: 13, title: "Software" },
      { id: 14, title: "Soundtracks" },
      { id: 15, title: "Virtual Reality" },
      { id: 16, title: "VR Hardware" },
      { id: 17, title: "Steam Deck" },
      { id: 18, title: "macOS" },
      { id: 19, title: "SteamOS + Linux" },
      { id: 20, title: "For PC Cafés" },
    ],
    show: false,
  },
  {
    id: 3,
    title: "Genres",
    level: 2,
    list: [
      {
        title: "Action",
        list: [
          { id: 21, title: "Action Rogue-Like" },
          { id: 22, title: "Arcade & Rhythm" },
          { id: 23, title: "Beat ‘Em Up" },
          { id: 24, title: "Fighting & Martial Arts" },
          { id: 25, title: "First-Person Shooter" },
          { id: 26, title: "Flat-former & Runner" },
          { id: 27, title: "Third-Person Shooter" },
        ],
        show: false,
      },
      {
        title: "Role-Playing",
        list: [
          { id: 28, title: "Action RPG" },
          { id: 29, title: "Adventure RPG" },
          { id: 30, title: "JRPG" },
          { id: 31, title: "Party-Based" },
          { id: 32, title: "Rogue-Like" },
          { id: 33, title: "Strategy RPG" },
          { id: 34, title: "Turn-Based" },
        ],
        show: false,
      },
      {
        title: "Strategy",
        list: [
          { id: 35, title: "Card & Board" },
          { id: 36, title: "City & Settlement" },
          { id: 37, title: "Grand & 4K" },
          { id: 38, title: "Military" },
          { id: 39, title: "Real-Time Strategy" },
          { id: 40, title: "Tower Defense" },
          { id: 41, title: "Turn-Based Strategy" },
        ],
        show: false,
      },
      {
        title: "Adventure & Casual",
        list: [
          { id: 42, title: "Adventure" },
          { id: 43, title: "Adventure RPG" },
          { id: 44, title: "Casual" },
          { id: 45, title: "Metroidvania" },
          { id: 46, title: "Puzzle" },
          { id: 47, title: "Story-Rich" },
          { id: 48, title: "Visual Novel" },
        ],
        show: false,
      },
      {
        title: "Simulation",
        list: [
          { id: 49, title: "Building & Automation" },
          { id: 50, title: "Business & Tycoon" },
          { id: 51, title: "Dating" },
          { id: 52, title: "Farming & Crafting" },
          { id: 53, title: "Life & Immersive" },
          { id: 54, title: "Sandbox & Physics" },
          { id: 55, title: "Space & Flight" },
        ],
        show: false,
      },
      {
        title: "Sports & Racing",
        list: [
          { id: 56, title: "All Sports" },
          { id: 57, title: "Fishing & Hunting" },
          { id: 58, title: "Individual Sports" },
          { id: 59, title: "Racing" },
          { id: 60, title: "Racing Sim" },
          { id: 61, title: "Sports Sim" },
          { id: 62, title: "Team Sports" },
        ],
        show: false,
      },
    ],
    show: false,
  },
  {
    id: 4,
    title: "Themes",
    level: 1,
    list: [
      { id: 63, title: "Anime" },
      { id: 64, title: "Horror" },
      { id: 65, title: "Mystery & Detective" },
      { id: 66, title: "Open World" },
      { id: 67, title: "Sci-Fi & Cyberpunk" },
      { id: 68, title: "Space" },
      { id: 69, title: "Survival" },
    ],
    show: false,
  },
  {
    id: 5,
    title: "Player support",
    level: 1,
    list: [
      { id: 70, title: "Cooperative" },
      { id: 71, title: "LAN" },
      { id: 72, title: "Local & Party" },
      { id: 73, title: "MMO" },
      { id: 74, title: "Single-player" },
      { id: 75, title: "Multiplayer" },
      { id: 76, title: "Online Competitive" },
    ],
    show: false,
  },
];

export const CATEGORY_LIST = [
  'All categories',
  'Action',
  'Adventure',
  'Card',
  'Metaverse',
  'MMORPG',
  'Puzzle',
  'Racing',
  'Simulation',
  'Sports',
  'Strategy',
  'Real-time Strategy',
  'Turn-based Strategy',
  'Others'
]
