export const marketActivitiesActions = {
  LOADING: 'MARKET_ACTIVITIES_LOADING',
  SUCCESS: 'MARKET_ACTIVITIES_SUCCESS',
  FAILURE: 'MARKET_ACTIVITIES_FAILURE'
}

export const discoverMarketActions = {
  LOADING: 'DISCOVER_MARKET_LOADING',
  SUCCESS: 'DISCOVER_MARKET_SUCCESS',
  FAILURE: 'DISCOVER_MARKET_FAILURE'
}
