const CREATE_AGGREGATOR_REQUEST = 'CREATE_AGGREGATOR_REQUEST';
const CREATE_AGGREGATOR_SUCCESS = 'CREATE_AGGREGATOR_SUCCESS';
const CREATE_AGGREGATOR_FAIL = 'CREATE_AGGREGATOR_FAIL';
const GET_AGGREGATOR_REQUEST = 'GET_AGGREGATOR_REQUEST';
const GET_AGGREGATOR_SUCCESS = 'GET_AGGREGATOR_SUCCESS';
const GET_AGGREGATOR_FAIL = 'GET_AGGREGATOR_FAIL';
const GET_TOKENOMIC_REQUEST = 'GET_TOKENOMIC_REQUEST';
const GET_TOKENOMIC_SUCCESS = 'GET_TOKENOMIC_SUCCESS';
const GET_TOKENOMIC_FAIL = 'GET_TOKENOMIC_FAIL';
const GET_PROJECT_REQUEST = 'GET_PROJECT_REQUEST';
const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
const GET_PROJECT_FAIL = 'GET_PROJECT_FAIL';
const DELETE_AGGREGATOR_REQUEST = 'DELETE_AGGREGATOR_REQUEST';
const DELETE_AGGREGATOR_SUCCESS = 'DELETE_AGGREGATOR_SUCCESS';
const DELETE_AGGREGATOR_FAIL = 'DELETE_AGGREGATOR_FAIL';

export const aggregatorAction = {
    CREATE_AGGREGATOR_REQUEST,
    CREATE_AGGREGATOR_SUCCESS,
    CREATE_AGGREGATOR_FAIL,
    GET_AGGREGATOR_REQUEST,
    GET_AGGREGATOR_SUCCESS,
    GET_AGGREGATOR_FAIL,
    DELETE_AGGREGATOR_SUCCESS,
    DELETE_AGGREGATOR_REQUEST,
    DELETE_AGGREGATOR_FAIL,
    GET_TOKENOMIC_REQUEST,
    GET_TOKENOMIC_SUCCESS,
    GET_TOKENOMIC_FAIL,
    GET_PROJECT_REQUEST,
    GET_PROJECT_SUCCESS,
    GET_PROJECT_FAIL

}
