const CREATE_COLLECTION_REQUEST = 'CREATE_COLLECTION_REQUEST';
const CREATE_COLLECTION_SUCCESS = 'CREATE_COLLECTION_SUCCESS';
const CREATE_COLLECTION_FAIL = 'CREATE_COLLECTION_FAIL';
const GET_COLLECTION_REQUEST = 'GET_COLLECTION_REQUEST';
const GET_COLLECTION_SUCCESS = 'GET_COLLECTION_SUCCESS';
const GET_COLLECTION_FAIL = 'GET_COLLECTION_FAIL';
const DELETE_COLLECTION_REQUEST = 'DELETE_COLLECTION_REQUEST';
const DELETE_COLLECTION_SUCCESS = 'DELETE_COLLECTION_SUCCESS';
const DELETE_COLLECTION_FAIL = 'DELETE_COLLECTION_FAIL';

export const collectionAction = {
    CREATE_COLLECTION_REQUEST,
    CREATE_COLLECTION_SUCCESS,
    CREATE_COLLECTION_FAIL,
    GET_COLLECTION_REQUEST,
    GET_COLLECTION_SUCCESS,
    GET_COLLECTION_FAIL,
    DELETE_COLLECTION_SUCCESS,
    DELETE_COLLECTION_REQUEST,
    DELETE_COLLECTION_FAIL

}
